export const formConfigs = {
  produits: {
    title: "Produits",
    dataKey: "produits",
    addRoute: "/produits/form",
    editRoute: "/produits/form",
    columns: [
      { header: "Sélectionner", key: "select" },
      { header: "Nom du produit", key: "nomProduit" },
      { header: "Catégorie de produit", key: "catégorieProduit" },
      { header: "Type", key: "Type" },
      { header: "Fiche de prix", key: "fichePrix" },
      { header: "Quantité disponible", key: "quantitéDisponible" },
      { header: "Quantité totale", key: "quantiteTotale" },
    ],
    buttons: [
      { text: "Ajouter", icon: '@/assets/svg/ajouter.tsx' },
      { text: "Modifier", icon: '@/assets/svg/modifier.tsx' },
      { text: "Supprimer", icon: '@/assets/svg/suprimer.tsx' },
    ],
    statusOptions: ["Produits actifs", "Produits inactifs"],
    filterOptions: ["Newest", "Oldest"],
    defaultStatus: "Produits actifs",
    defaultFilter: "Newest",
  },
  'fiche-de-prix': {
    title: "Fiche de prix",
    dataKey: "fichePrix",
    addRoute: "/fiche-de-prix/form",
    editRoute: "/fiche-de-prix/form",
    columns: [
      { header: "Sélectionner", key: "select" },
      { header: "Date de début", key: "dateDebut" },
      { header: "Date de fin", key: "dateFin" },
      { header: "Prix achat HT", key: "PrixAchatHt" },
      { header: "Prix achat TTC", key: "PrixAchatTtc" },
      { header: "Pourcentage précompte", key: "PourcentagePrecompte" },
      { header: "Pourcentage TVA", key: "PourcentageTva" },
      { header: "Prix vente TTC", key: "PrixVenteTtc" },
      { header: "Marge TTC", key: "margeTtc" },
      { header: "Pourcentage marge", key: "pourcentageMarge" },
    ],
    buttons: [
      { text: "Ajouter", icon: '@/assets/svg/ajouter.tsx' },
      { text: "Modifier", icon: '@/assets/svg/modifier.tsx' },
      { text: "Supprimer", icon: '@/assets/svg/suprimer.tsx' },
    ],
    statusOptions: ["Fiches actives", "Fiches inactives"],
    filterOptions: ["Newest", "Oldest"],
    defaultStatus: "Fiches actives",
    defaultFilter: "Newest",
  },
};
